- name: Flake8 линтерин орнотуу
        run: pip install flake8

      - name: Коддун сапатын текшерүү (Static Analysis)
        run: |
          # Биринчи: оор каталарды текшерүү (Syntax errors)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
          # Экинчи: стилдик каталарды текшерүү (PEP 8)
          # --exit-zero болсо, стилдик ката үчүн пайплайн токтобойт, бирок эскертүү берет
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
