name: Build and Release

on:
  push:
    tags:
      - 'v*' # Качан гана v1.0 сыяктуу тег коюлганда иштейт

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Artifact (Zip)
        run: |
          # Программаны жана логдорду архивге чогултуу
          zip -r project-v1.zip main.py geometry.py calc.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: project-v1.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
